"""empty message

Revision ID: 37361b7c8170
Revises: ee3ae9ab60f9
Create Date: 2024-07-03 13:58:59.281670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37361b7c8170'
down_revision = 'ee3ae9ab60f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('director', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name=op.f('fk_watchlist_table_user_id_users_table')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movies_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_movies_table_user_id_users_table'), 'users_table', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_movies_table_user_id_users_table'), type_='foreignkey')
        batch_op.alter_column('rating',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('user_id')

    op.drop_table('watchlist_table')
    # ### end Alembic commands ###
